[project]
name = "classroom"
version = "0.1.0"
description = "GitHub course administration tool"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32",
    "keyring>=25.6",
    "platformdirs>=4.0"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
classroom = "classroom.__main__:main"

